# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomhub < Formula
  desc "CLI for SBOMHub - SBOM generation and vulnerability scanning"
  homepage "https://sbomhub.app"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youichi-uda/sbomhub-cli/releases/download/v0.1.1/sbomhub-cli_darwin_amd64.tar.gz"
      sha256 "6c85c32b2992e0512cf773812f7f2057d2a00db9e12f2a7a950131f6fc72b9d9"

      def install
        bin.install "sbomhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youichi-uda/sbomhub-cli/releases/download/v0.1.1/sbomhub-cli_darwin_arm64.tar.gz"
      sha256 "97cee41c072512184cb872e262b8f993ba5578eaa681edbe0c88d73a4769024a"

      def install
        bin.install "sbomhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youichi-uda/sbomhub-cli/releases/download/v0.1.1/sbomhub-cli_linux_amd64.tar.gz"
      sha256 "444b25a67a391dc9a8b63bc5135c0743d9c25a726681a831dfbcc78f06b8cefd"
      def install
        bin.install "sbomhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youichi-uda/sbomhub-cli/releases/download/v0.1.1/sbomhub-cli_linux_arm64.tar.gz"
      sha256 "538684643fc9c3b566e9d08b8f086082ef9adf932b9215d34d89fab6b5cbee29"
      def install
        bin.install "sbomhub"
      end
    end
  end

  test do
    system "#{bin}/sbomhub", "version"
  end
end
