# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomhub < Formula
  desc "CLI for SBOMHub - SBOM generation and vulnerability scanning"
  homepage "https://sbomhub.app"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youichi-uda/sbomhub-cli/releases/download/v0.1.0/sbomhub-cli_darwin_amd64.tar.gz"
      sha256 "b728ea8e6898a792bb79f0a33f05a950fa603d42352e0b1cceeed615f33aa1a8"

      def install
        bin.install "sbomhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youichi-uda/sbomhub-cli/releases/download/v0.1.0/sbomhub-cli_darwin_arm64.tar.gz"
      sha256 "844e0384140f4746a8b84408228a96a9ef53c839d9c15aac3415f46634748bb5"

      def install
        bin.install "sbomhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/youichi-uda/sbomhub-cli/releases/download/v0.1.0/sbomhub-cli_linux_amd64.tar.gz"
      sha256 "1c42849313454ee65d11cd7921a84a3d15bbf44f0f1543e9996f8823f4ad770b"
      def install
        bin.install "sbomhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youichi-uda/sbomhub-cli/releases/download/v0.1.0/sbomhub-cli_linux_arm64.tar.gz"
      sha256 "f4c632d00e05f2ee7c4c932b50b0047560ca563d92f04e9833d37372418403b3"
      def install
        bin.install "sbomhub"
      end
    end
  end

  test do
    system "#{bin}/sbomhub", "version"
  end
end
